[package]
name = "relayer"
version = "0.1.0"
edition = "2018"
authors = [
  "Anca Zamfir <anca@interchain.io>",
  "Romain Ruetschi <romain@informal.systems>"
]

[dependencies]
relayer-modules = { path = "../../modules" }
tendermint = { path = "../../../tendermint-rs/tendermint/" }
#tendermint = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "tendermint/v0.33" }
anomaly = "0.2.0"
async-trait = "0.1.24"
humantime-serde = "1.0.0"
prost-amino = { path = "../../../../tendermint/amino_rs" } # "0.5"
prost-amino-derive= { path = "../../../../tendermint/amino_rs/prost-amino-derive" } # "0.5"
serde = "1.0.97"
serde_json = "1"
serde_cbor = "0.11.1"
serde_derive = "1.0"
sled = { version = "0.31.0", features = ["no_metrics", "no_logs"] }
thiserror = "1.0.11"
toml = "0.5"
tracing = "0.1.13"
stdtx = { path = "../../../../iqlusioninc/crates/stdtx" } # "0.1.0"
subtle-encoding = { version = "0.5", features = ["bech32-preview"] }


[dev-dependencies]
tokio = { version = "0.2.13", features = ["macros"] }
